### ISSUE TITLE
Why the need of EnumChoiceFieldException?

### ISSUE THREAD

**Issue by vstoykov** [HackSoftware/django-enum-choices#30]
Why custom `EnumChoiceFieldException` is used when builtin types are sufficient ([`TypeError`](https://docs.python.org/3/library/exceptions.html#TypeError) and [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError)?

Example replacements:
- `TypeError`s - [`utils.validate_built_choices`](https://github.com/HackSoftware/django-enum-choices/blob/v2.0.1/django_enum_choices/utils.py#L46-L64),[`EnumChoiceField._get_choice_builder`](https://github.com/HackSoftware/django-enum-choices/blob/v2.0.1/django_enum_choices/fields.py#L49)
- `ValueError`s - [`EnumChoiceField.__init__`](https://github.com/HackSoftware/django-enum-choices/blob/v2.0.1/django_enum_choices/fields.py#L22)

If you think that `TypeError` can be too much then `ValueError` can be enough in all cases but I still don't think that extra exception is worth it.

Probably I'm missing something (the way how you are using the library in your projects).  If you think that my suggestions are meaningless just ignore them. Still if there are real reasons I will be glad if you share them with the audience.

**Comment by RadoRado** [comment]
@vstoykov There's a simple reason for that:

* If you want to try/except something explicitly raised by the library, you can do that, by having the `EnumChoiceFieldException`
* If we raise `TypeError` / `ValueError`, there's no guarantee that this is the explicitly raised exception by us & not some bug / other Python code failing

**Comment by vstoykov** [comment]
In the case for the `EnumChoiceField.__init__` it is almost always used in model definitions which are executed at import time. I'm not sure that someone will use use `try:..execpt:..` there. Raising the proper `ValueError` will indicate to the developer that they are not using some field correctly and from the traceback they will see where.

For `EnumChoiceField._get_choice_builder` it's "private" method and no other library/project should use it. Actually this method is called from the `EnumChoiceField.__init__` and the above observation should apply

For `utils.validate_built_choices` is more complicated because it is in `utils` and other 3th party library can use it directly but this library can guard the call with `try:..except:..` if it is needed. Although currently `utils.validate_built_choices` is also only called during `__init__` of the `EnumChoiceFIeld` (model and form) and basically the above observations should also apply here.

I understand that in theory "If you want to try/except something explicitly raised by the library, you can do that, by having the CustomExceptionNameHere" but in practice currently it looks more like it is overengineered IMHO.

**Comment by RadoRado** [comment]
I think we are bike shedding and there's not much value in that argument. From our experience, having a custom exception works better :+1:
