### ISSUE TITLE
Enum field validator not aware of customizable choice builder

### ISSUE THREAD

**Issue by alieh-rymasheuski** [HackSoftware/django-enum-choices#42]
Minimal (but untested) case to reproduce the issue:
```
import enum

from django.db import models
from django_enum_choices.choice_builders import attribute_value
from django_enum_choices.fields import EnumChoiceField


class Neo(models.Model):
    class PillChoice(enum.Enum):
        red = "Red"
        blue = "Blue"
        neither = "Chose neither pill"  # len(value) > max len(attr) of all attrs

    pill = EnumChoiceField(PillChoice, choice_builder=attribute_value)
```

We [validate `len(Neo.neither.value)`](https://github.com/HackSoftware/django-enum-choices/blob/0061f9d6ab7a80b2f6ffcaca988d3a02c1aa9a0b/django_enum_choices/validators.py#L12) while [storing `Neo.neither.name`](https://github.com/HackSoftware/django-enum-choices/blob/0061f9d6ab7a80b2f6ffcaca988d3a02c1aa9a0b/django_enum_choices/choice_builders.py#L21) and [setting `max_length=len("neither")`](https://github.com/HackSoftware/django-enum-choices/blob/0061f9d6ab7a80b2f6ffcaca988d3a02c1aa9a0b/django_enum_choices/fields.py#L76)

**Comment by slavov-v** [comment]
Fixed in https://github.com/HackSoftware/django-enum-choices/pull/44
