### ISSUE TITLE
Empty strings are not converted to enums via admin interface

### ISSUE THREAD

**Issue by SaturnFromTitan** [HackSoftware/django-enum-choices#50]
We encountered a pretty confusing bug today: When doing changes via the admin interface, sometimes some of our fields would contain a string instead of a proper enum value.

The same field on the same instance would be returned as an enum on a regular value, but as an empty string when the enum representation of an empty string is returned.

After some tinkering, we found that [this piece of code](https://github.com/HackSoftware/django-enum-choices/blob/master/django_enum_choices/forms.py#L30-L37) might be the problem:
```
    def to_python(self, value):
        if value is None:
            return

        if value in self.empty_values:
            return ''

        return self._enum_from_input_value(value) or value
```
In our case value is an empty string so `value in self.empty_values` is True and the function returns an empty string instead of the actual enum representation.

We suggest changing the second `if` flow to
```
        if value in self.empty_values:
            value = ''
```
so that the empty representation is standardised and can be translated properly to an enum with `_enum_from_input_value`.

Do you agree with the suggested solution?

**Comment by SaturnFromTitan** [comment]
The PR of @wiedi resolves the issue for us. For now, we reference his branch in our dependencies, but it would be great to get it merged. Before adding a test case to the PR though, it'd be great to get some general feedback from a maintainer

**Comment by slavov-v** [comment]
Fixed in https://github.com/HackSoftware/django-enum-choices/pull/51
