### ISSUE TITLE
Changing/removing enum values and applying migrations results in erroneous database state

### ISSUE THREAD

**Issue by pgergov** [HackSoftware/django-enum-choices#53]
## Issue description

Changing an enum value and migrating the databse can lead to objects in the database containing the old enum value. No warning is shown during the migration process. Accessing such object results in `ValidationError`.

## Steps to reproduce

Let's have the following enum:

```python
class ExampleEnum(Enum):
    BAR = 'bar'
```

And a model that uses it:

```python
class ExampleModel(Model):
    example_field = EnumChoiceField(ExampleEnum)
```

Create an instance(s) of the model:

```python
ExampleModel.objects.create(example_field=ExampleEnum.BAR)
```

Change existing value in `ExampleEnum`:

```
class ExampleEnum(Enum):
    BAR = 'bar_updated'
```

Make a data migration and run it. Try to access the existing instance:

```python
ExampleModel.objects.first()
```

The following error occurs:

> ValidationError: ["Value bar not found in <enum 'ExampleEnum'>"]

## Proposed solution

Document how to avoid this. Example:

At any given point of time all instances of a model that has `EnumChoiceField` **must** have a value that is currently present in the Enum class. If an enum value is changed/removed from the class ➡️ migration can be made and the database can be migrated successfully. No error or warning will be raised at this point, but future access to an instances containing the changed/removed enum value will result in a `ValidationError`:

> ValidationError: ["Value {changed/removed-value-here} not found in <enum '{Enum-class-name-here}'>"]

If you need to change existing Enum value, or completely remove it, a data migration needs to be done first. All model instances that contain the enum value that's going to be changed, or removed, must be migrated to an enum value that exists in the Enum.

*Note* If the enum value is changed and the database migration has passed, you can still migrate the instances that contain the old enum value. You need to locate their ids and do: 

```python
YourModelName.objects.filter(id__in=[ids-of-instances-with-old-enum-value-here]).update(enum_field=<new-enum-value-here>)
```

**Comment by slavov-v** [comment]
Addressed in https://github.com/HackSoftware/django-enum-choices/pull/54
