### ISSUE TITLE
Empty string not supported as value when having blank=True

### ISSUE THREAD

**Issue by wencakisa** [HackSoftware/django-enum-choices#55]
## Scenario

```python
from django.db import models

from enum import Enum

from django_enum_choices.fields import EnumChoiceField


class MyEnum(Enum):
    A = 'A'


class MyModel(models.Model):
    field = EnumChoiceField(MyEnum, blank=True, null=True)
```

With the following setup, we're trying to construct an enum choice field that can also **be blank**.

Django version: `2.2.12`

## Problem

The problem that we've hit is when we've tried to create an instance of `MyModel` with `field = ''`, we receive the following error: <pre>Value  not found in MyEnum</pre>

It says that an empty string (`''`) is an invalid value for the field, which is confusing as we're having `blank=True` already.

## Potential fix

Tracing down the problem, we've reached its origin:

```python
class EnumChoiceField(CharField):
    ...

    def to_enum_value(self, value):
        if value is None:  # <------------
            return

        for choice in self.enum_class:
            # Check if the value from the built choice matches the passed one
            if value_from_built_choice(self.choice_builder(choice)) == value:
                return choice

        raise ValidationError(
            _('Value {} not found in {}'.format(value, self.enum_class))
        )
```

When checking the value in the `to_enum_value` method, it is compared with `is None`. Which, when we have an empty string, evaluates to `False`. Thus the method continues with the interpretation and finally reaches the `raise ValidationError` statement.

When changing this line from:

```python
if value is None:
```

to:

```python
if not value:
```

It works as expected because it evaluates the value to **falsy** since it does not differentiate between `None` and `''` (empty string).

---

Is this an expected behaviour?

**Comment by Jusstas** [comment]
Agreed, in my project I run into the same problem, to fix it I had to extend `EnumChoiceField` and apply exact same fix as @wencakisa proposed.

**Comment by RadoRado** [comment]
Closing this since the project is no-longer maintained, due to the functionality existing natively in Django >= 3 raised_hands
