### ISSUE TITLE
Document that this is now included in Django

### ISSUE THREAD

**Issue by adamchainz** [HackSoftware/django-enum-choices#58]
Django 3.0 includes enumeration types which do mostly the same thing as this library: https://adamj.eu/tech/2020/01/27/moving-to-django-3-field-choices-enumeration-types/

**Comment by RadoRado** [comment]
@adamchainz Yep, we are going to do that soon :P

**Comment by RadoRado** [comment]
Closing this since the project is no-longer maintained, due to the functionality existing natively in Django >= 3 raised_hands
