### ISSUE TITLE
Support for enum aliases

### ISSUE THREAD

**Issue by VietHo** [HackSoftware/django-enum-choices#62]
**Scenario**

DB is managed by someone else

MyTable.my_column contains values among ['Q1', 'Q01', 'Q2']

```
class MyEnum(Enum):
    Q1 = 'Q1'
    Q01 = 'Q1'
    Q2 = 'Q2'
```
**Problem**

django.core.exceptions.ValidationError: ["Value Q01 not found in <enum 'MyEnum'>"]

**Solution**

I haven't looked into a detailed solution, but I guess that it has to do with building the choices from `enum_class.__members__ `rather that iterating over enum_class

However I think it would break the choice_builder mechanic

If someone has a workaround, I'll take it.

**Comment by RadoRado** [comment]
Closing this since the project is no-longer maintained, due to the functionality existing natively in Django >= 3 raised_hands
