### ISSUE TITLE
Support for default argument

### ISSUE THREAD

**Issue by javadnikbakht** [HackSoftware/django-enum-choices#63]
I use this package for a project that i need have a default argument to pass one of enum choices to set as the first value of one that field in a model like other django classes and  something like below e.g : 

`status = EnumChoiceField(StudentStatus, choice_builder=attribute_value, default=StudendStatus.Studying,verbose_name='student status')`

and this feature is exactly like other base django models classes like CharField or IntegerField etc.

**Comment by RadoRado** [comment]
Closing this since the project is no-longer maintained, due to the functionality existing natively in Django >= 3 raised_hands
