### ISSUE TITLE
Further improve README.md

### ISSUE THREAD

**Issue by RadoRado** [HackSoftware/django-enum-choices#8]
- More examples / folder with examples
- Examples with `auto()`
- Describe corner cases (change the values without data migration)

**Comment by wencakisa** [comment]
@RadoRado When importing Django's `models` package in [**Basic Usage** section in README.md](https://github.com/HackSoftware/django-enum-choices#basic-usage) it is mistyped:

It is `from django import models` but it actually needs to be `from django.db import models`.

😃

**Comment by RadoRado** [comment]
@wencakisa thanks, good catch, will fix it :+1:

**Comment by slavov-v** [comment]
Installation should be `pip install django-enum-choices` instead of `pip install django_enum_choices`.

**Comment by slavov-v** [comment]
Examples with `MultipleEnumChoiceField`
